In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#map csv
austin = "CSV/austin.csv"
#austin_df = pd.read_csv(austin)
austin_df = pd.read_csv(austin, encoding = 'latin-1')
austin_df.head()

,Unnamed: 0,Animal ID,Name_intake,DateTime_intake,MonthYear_intake,Found_Location,Intake_Type,IntakeCondition,Animal_Type_intake,Sex,...,beagle,terrier,boxer,poodle,rottweiler,dachshund,chihuahua,pit bull,DateTime_length,Days_length
0,0,A730601,NaN,7/7/2016 12:11,7/7/2016 12:11,1109 Shady Ln in Austin (TX),Stray,Normal,Cat,Intact Male,...,0,0,0,0,0,0,0,0,0 days 20:49:00.000000000,0-7 days
1,1,A683644,*Zoey,7/13/2014 11:02,7/13/2014 11:02,Austin (TX),Owner Surrender,Nursing,Dog,Intact Female,...,0,0,0,0,0,0,0,0,115 days 23:04:00.000000000,12 weeks - 6 months
2,2,A676515,Rico,4/11/2014 8:45,4/11/2014 8:45,615 E. Wonsley in Austin (TX),Stray,Normal,Dog,Intact Male,...,0,0,0,0,0,0,0,1,3 days 09:53:00.000000000,0-7 days
3,3,A742953,NaN,1/31/2017 13:30,1/31/2017 13:30,S Hwy 183 And Thompson Lane in Austin (TX),Stray,Normal,Dog,Intact Male,...,0,0,0,0,0,0,0,0,4 days 00:47:00.000000000,0-7 days
4,4,A679549,*Gilbert,5/22/2014 15:43,5/22/2014 15:43,124 W Anderson in Austin (TX),Stray,Normal,Cat,Intact Male,...,0,0,0,0,0,0,0,0,24 days 22:11:00.000000000,3-6 weeks

In [5]:
dog_df = austin_df.loc[(austin_df['Animal_Type_intake'] == "Dog"), : ]
dog_df.head()

,Unnamed: 0,Animal ID,Name_intake,DateTime_intake,MonthYear_intake,Found_Location,Intake_Type,IntakeCondition,Animal_Type_intake,Sex,...,beagle,terrier,boxer,poodle,rottweiler,dachshund,chihuahua,pit bull,DateTime_length,Days_length
1,1,A683644,*Zoey,7/13/2014 11:02,7/13/2014 11:02,Austin (TX),Owner Surrender,Nursing,Dog,Intact Female,...,0,0,0,0,0,0,0,0,115 days 23:04:00.000000000,12 weeks - 6 months
2,2,A676515,Rico,4/11/2014 8:45,4/11/2014 8:45,615 E. Wonsley in Austin (TX),Stray,Normal,Dog,Intact Male,...,0,0,0,0,0,0,0,1,3 days 09:53:00.000000000,0-7 days
3,3,A742953,NaN,1/31/2017 13:30,1/31/2017 13:30,S Hwy 183 And Thompson Lane in Austin (TX),Stray,Normal,Dog,Intact Male,...,0,0,0,0,0,0,0,0,4 days 00:47:00.000000000,0-7 days
11,11,A692161,George,11/15/2014 15:18,11/15/2014 15:18,Avenue G/42Nd in Austin (TX),Owner Surrender,Normal,Dog,Intact Male,...,0,0,0,0,0,0,0,1,6 days 03:37:00.000000000,0-7 days
14,14,A720597,*Franklin,2/12/2016 14:35,2/12/2016 14:35,8413 Danville Dr in Austin (TX),Stray,Injured,Dog,Intact Male,...,0,0,0,0,0,0,0,1,7 days 01:45:00.000000000,1-3 weeks

In [6]:
dog_df["Age"].value_counts()
#Make Bins for Age
#hp_bins = [180, 200, 350, 400]
#hp_labels = ["Slow", "Decent", "Fast"]

1 year       9945
2 years      8803
3 years      4623
4 years      2729
5 years      2462
1 month      2068
2 months     1743
6 years      1615
7 years      1356
8 years      1184
4 months     1126
5 months     1099
9 months      949
7 months      847
6 months      831
10 years      815
3 months      785
9 years       713
10 months     693
8 months      636
11 months     539
12 years      407
11 years      367
4 weeks       253
13 years      215
0 years       179
14 years      163
1 week        125
15 years      122
2 weeks        98
1 day          96
3 weeks        88
4 days         64
1 weeks        63
16 years       63
2 days         55
3 days         46
5 weeks        32
5 days         29
6 days         28
17 years       24
18 years       12
19 years        6
20 years        1
Name: Age, dtype: int64