In [6]:
import pandas as pd
import numpy as np

In [9]:
#export csvs 
# Save file path to variable
intake = "CSV/intake.csv"
outcome = "CSV/outcome.csv"
intake_df = pd.read_csv(intake)
outcome_df = pd.read_csv(outcome)
intake_df.head()

,Animal ID,Name,DateTime,MonthYear,Found Location,Intake Type,Intake Condition,Animal Type,Sex upon Intake,Age upon Intake,Breed,Color
0,A748291,*Madison,5/1/2017 14:26,5/1/2017 14:26,S Pleasant Valley Rd And E Riverside Dr in Aus...,Stray,Normal,Dog,Intact Female,10 months,Pit Bull Mix,Black
1,A750529,NaN,5/28/2017 13:22,5/28/2017 13:22,8312 North Ih 35 in Austin (TX),Stray,Normal,Dog,Intact Female,5 months,Miniature Schnauzer Mix,White/Cream
2,A730601,NaN,7/7/2016 12:11,7/7/2016 12:11,1109 Shady Ln in Austin (TX),Stray,Normal,Cat,Intact Male,7 months,Domestic Shorthair Mix,Blue Tabby
3,A748238,NaN,5/1/2017 10:53,5/1/2017 10:53,Airport Blvd And Oak Springs Dr in Austin (TX),Stray,Normal,Dog,Intact Male,3 years,Bichon Frise Mix,White
4,A683644,*Zoey,7/13/2014 11:02,7/13/2014 11:02,Austin (TX),Owner Surrender,Nursing,Dog,Intact Female,4 weeks,Border Collie Mix,Brown/White

In [13]:
#merge the two data framese
animal_df = pd.merge(intake_df, outcome_df, on="Animal ID", how="outer")